<?php

return [
    'roles' => [
        'admin' => 'Admin',
        'operator' => 'Operator',
        'guru' => 'Guru',
        'siswa' => 'Siswa',
        'wali_murid' => 'Wali Murid',
    ],

    'permissions' => [
        'admin' => ['*'],
        'operator' => [
            'dashboard.view',
            'guru.*',
            'kelas.*',
            'mapel.*',
            'jam_pelajaran.*',
            'tahun_pelajaran.*',
            'jadwal.*',
            'absensi.*',
            'surat_masuk.*',
            'surat_keluar.*',
            'template_surat.*',
            'tasks.*',
            'sarana.*',
            'kategori_sarana.*',
            'siswa.*',
            'buku_induk.*',
            'raport.*',
            'arsip_akademik.*',
        ],
        'guru' => [
            'dashboard.view',
            'jadwal.view',
            'absensi.view',
            'absensi.create',
            'absensi.update',
            'absensi.export',
            'tasks.view',
            'tasks.create',
            'tasks.update',
            'sarana.view',
            'siswa.view',
            'buku_induk.view',
            'buku_induk.export',
            'raport.view',
            'raport.create',
            'raport.update',
            'raport.export',
        ],
        'siswa' => [
            'dashboard.view',
            'jadwal.view',
            'raport.view',
        ],
        'wali_murid' => [
            'dashboard.view',
            'raport.view',
        ],
    ],

    'backup' => [
        'enabled' => env('EMADRASAH_BACKUP_ENABLED', true),
        'path' => env('EMADRASAH_BACKUP_PATH', storage_path('app/private/backups')),
        'retention_days' => (int) env('EMADRASAH_BACKUP_RETENTION_DAYS', 14),
        'database_connection' => env('EMADRASAH_BACKUP_DB_CONNECTION'),
        'include_uploads' => env('EMADRASAH_BACKUP_INCLUDE_UPLOADS', true),
        'upload_disk' => env('EMADRASAH_BACKUP_UPLOAD_DISK', 'public'),
        'upload_paths' => [
            'arsip-akademik',
            'sarana',
            'siswa-dokumen',
            'surat-keluar',
            'surat-masuk',
            'task-attachments',
        ],
        'mysqldump_binary' => env('EMADRASAH_MYSQLDUMP_BINARY', 'mysqldump'),
        'pg_dump_binary' => env('EMADRASAH_PG_DUMP_BINARY', 'pg_dump'),
    ],
];
